# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ChannelsTest1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PusherSwift', '~> 8.0'

  # Pods for ChannelsTest1

end
